version: '3'

services:
  api-gymgo:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_DATABASE=gymgo